### ISSUE TITLE
babel 7 사용자를 위한 안내 추가를 건의드립니다!

### ISSUE THREAD

**Issue by jjunyjjuny** [woowa-techcamp-2021/woowahan-jsx#19]
![스크린샷 2021-07-31 오후 6 41 57](https://user-images.githubusercontent.com/41738385/127735895-c36ceea4-6f56-499e-bec0-404c0bc26a43.png)

제공해주신 src 디렉토리 내에 있는 `jsx.js`, `jsx.ts`는 이미 트랜스파일링이 된 상태의 파일인데, 혹시 트랜스파일링 단계에서 babel 버전이 `6.x.x`이었나요? 그로 인해 `core-js`의 버전이 `3`인거 같습니다. 해당 파일은 사용자의 프로젝트에서 다시 번들/트랜스파일링의 대상이 될 수 있기 때문에 문제가 발생하는거 같습니다!

저는 `babel 7`을 사용중인데, `babel 7`의  기본 `core-js` 버전이 `2`라서 그대로 가져다 쓰면 `core-js not found` 에러가 발생하더라구요.

`babel` 설정 파일에 `corejs` 버전을 3으로 명시함으로써 해결했습니다!

```
{
	"presets": [
		[
			"@babel/preset-env",
			{
				"targets": "> 1%, not dead",
				"useBuiltIns": "usage",
				"corejs": 3 // babel 7 버전부터는 기본이 2이기 때문에 3으로 지정해줘야 함.
			}
		]
	]
}

```

문제 해결에 도움이 된 아티클 링크입니다

https://e2xist.tistory.com/741

**Comment by gomjellie** [comment]
오... 이슈 감사합니다

**Comment by gomjellie** [comment]
```sh
tsc ./src/jsx.ts 
```
항상 위 명령어로 ts -> js 트랜스파일을 했어요.

**Comment by gomjellie** [comment]
이거 제가 트랜스파일 방법을 바꿔야할지 아니면 install 문서에  corejs: 3으로 사용하라고 명시를 해야될지 판단이 안서는데 어떤게 좋을까요?

**Comment by jjunyjjuny** [comment]
바벨 6, 바벨7로 각자 트랜스파일링해서 버전별로 제공하는건 어떤가요? 저두 잘 모르겠네용 ,,

**Comment by gomjellie** [comment]
closed by #22
