### ISSUE TITLE
NPM 등록 건의드립니다.

### ISSUE THREAD

**Issue by sshrik** [woowa-techcamp-2021/woowahan-jsx#21]
복사해서 사용하는것보다 npm 등록 이후 npm에서 다운받아 module 형식으로 쓰게 해보는건 어떨까요?

[내 패키지 npm 등록하기](https://heropy.blog/2019/01/31/node-js-npm-module-publish/) 링크를 보면서 올려도 좋을 것 같습니다.

사실 개인 프로젝트에 한번 써보고싶은데, npm으로 되어있으면 누가 개발했는지 등을 알 수 있어서 좋을 것 같습니다~

**Comment by gomjellie** [comment]
오호 한번 패키지 등록도 해볼게요~ 감사합니다 👍

**Comment by gomjellie** [comment]
패키지 등록했습니다 👍
